[project]
name = "oncall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-config>=0.1.2",
    "wxpython>=4.2.3",
]
